# Generated by Django 6.0.1 on 2026-01-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='product_code',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
